const nodemailer = require('nodemailer');

async function sendTestEmail() {
  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true, // SSL
    auth: {
      user: 'kanzariyapratik124@gmail.com',
      pass: 'xrdtkwzkayzeerkf'
    }
  });

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f1f5f9; margin: 0; padding: 20px; color: #1e293b; }
    .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); }
    .header { background: linear-gradient(135deg, #4f46e5, #3730a3); padding: 30px; text-align: center; color: #ffffff; }
    .header h1 { margin: 0; font-size: 22px; font-weight: 800; letter-spacing: -0.5px; }
    .header p { margin: 6px 0 0 0; font-size: 13px; opacity: 0.9; }
    .content { padding: 30px; line-height: 1.6; }
    .badge-box { background: #fef2f2; border: 1px solid #fecaca; border-radius: 12px; padding: 16px; margin: 20px 0; }
    .badge-title { font-size: 15px; font-weight: 700; color: #991b1b; }
    .badge-desc { font-size: 13px; color: #7f1d1d; margin-top: 4px; }
    .details-table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 13px; }
    .details-table td { padding: 10px 12px; border-bottom: 1px solid #f1f5f9; }
    .details-table td.label { font-weight: 600; color: #64748b; width: 40%; }
    .details-table td.val { font-weight: 700; color: #0f172a; font-family: monospace; }
    .cta-box { background: #f8fafc; border-radius: 12px; padding: 16px; text-align: center; margin-top: 25px; border: 1px solid #e2e8f0; font-size: 12px; color: #475569; }
    .footer { background: #f8fafc; padding: 20px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🎓 Learnmore Technologies</h1>
      <p>Faculty Attendance & Monitoring Operations</p>
    </div>
    
    <div class="content">
      <p>Dear <strong>Amit Verma</strong>,</p>
      
      <p>This is an automated operational notification regarding today's faculty login status.</p>
      
      <div class="badge-box">
        <div class="badge-title">⚠️ Notice of Uninformed Absence (12:00 PM Cutoff)</div>
        <div class="badge-desc">
          Our attendance monitoring engine recorded that you have not logged in to the Faculty Portal by the standard 12:00 PM cutoff today (26 Aug 2026), and no prior approved leave was registered in the system.
        </div>
      </div>
      
      <table class="details-table">
        <tr>
          <td class="label">Trainer Name:</td>
          <td class="val">Amit Verma (Database & SQL Faculty)</td>
        </tr>
        <tr>
          <td class="label">Date:</td>
          <td class="val">26 Aug 2026</td>
        </tr>
        <tr>
          <td class="label">Cutoff Evaluated:</td>
          <td class="val">12:00 PM (IST)</td>
        </tr>
        <tr>
          <td class="label">Recorded Status:</td>
          <td class="val" style="color: #dc2626; font-weight: 800;">🔴 NOT LOGGED IN / ABSENT</td>
        </tr>
      </table>
      
      <div class="cta-box">
        <strong>Next Steps:</strong> If you are unable to conduct your scheduled batches today or are facing an emergency, please submit a regularized leave application in the portal or contact institute administration immediately.
      </div>
    </div>
    
    <div class="footer">
      This is an automated system email generated by Learnmore Faculty Portal. Please do not reply directly to this email.
    </div>
  </div>
</body>
</html>
  `;

  console.log('Sending live test email to kanzariyapratik124@gmail.com...');
  const info = await transporter.sendMail({
    from: '"Learnmore Technologies" <kanzariyapratik124@gmail.com>',
    to: 'kanzariyapratik124@gmail.com',
    subject: '⚠️ Notice of Uninformed Absence - 12:00 PM Cutoff Alert',
    html
  });

  console.log('Email successfully sent! Message ID:', info.messageId);
}

sendTestEmail().catch(err => {
  console.error('Error sending email:', err);
});
