# Generated by Django 5.2.13 on 2026-09-09 09:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('trainer', 'Trainer')], default='trainer', max_length=20)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('hourly_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppBroadcastLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=100)),
                ('batch_name', models.CharField(max_length=200)),
                ('trainer_name', models.CharField(max_length=150)),
                ('group_name', models.CharField(max_length=200)),
                ('message_preview', models.TextField()),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('failed', 'Failed')], default='delivered', max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LiveActivity',
            fields=[
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='live_activity', serialize=False, to='api.userprofile')),
                ('trainer_name', models.CharField(max_length=150)),
                ('status', models.CharField(default='idle', max_length=30)),
                ('current_task_title', models.CharField(blank=True, max_length=200, null=True)),
                ('current_batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_batch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idle_minutes_current', models.IntegerField(default=0)),
                ('total_idle_today_minutes', models.IntegerField(default=0)),
                ('total_teaching_today_minutes', models.IntegerField(default=0)),
                ('total_task_today_minutes', models.IntegerField(default=0)),
                ('is_logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('weekoff', 'Week Off'), ('optional_holiday', 'Optional Holiday')], default='casual', max_length=30)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('trainer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('total_hours', models.FloatField(default=40.0)),
                ('total_students', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_type', models.CharField(choices=[('training', 'Training'), ('other', 'Other')], default='training', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('whatsapp_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_group_link', models.TextField(blank=True, null=True)),
                ('auto_whatsapp_group', models.BooleanField(default=True)),
                ('timing', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('doubt_solving', 'Doubt Solving'), ('paper_checking', 'Paper Checking'), ('calling', 'Calling'), ('curriculum_planning', 'Curriculum Planning'), ('lab_assistance', 'Lab Assistance'), ('other', 'Other')], default='other', max_length=50)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerAttendance',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.CharField(max_length=50)),
                ('mark_in_time', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_out_time', models.CharField(blank=True, max_length=50, null=True)),
                ('working_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_in', models.TextField(blank=True, null=True)),
                ('photo_out', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('day_status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('pending', 'Pending'), ('absent', 'Absent'), ('weekoff', 'Week Off'), ('holiday', 'Holiday')], default='present', max_length=20)),
                ('total_work_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('selected_topics', models.JSONField(blank=True, default=list)),
                ('session_date', models.CharField(default=django.utils.timezone.now, max_length=50)),
                ('hours_taken', models.FloatField(default=1.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_students_present', models.IntegerField(default=0)),
                ('total_students_absent', models.IntegerField(default=0)),
                ('total_students_leave', models.IntegerField(default=0)),
                ('students_attendance', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='api.batch')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='api.userprofile')),
            ],
        ),
    ]
