# Generated by Django 5.2.13 on 2026-09-10 09:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceGroupConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('group_id', models.CharField(default='120363231853245188@g.us', max_length=100)),
                ('group_name', models.CharField(default='LEARNMORE-Login-Logout', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_hours', models.FloatField(default=40.0)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerLeaveBalance',
            fields=[
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leave_balance', serialize=False, to='api.userprofile')),
                ('trainer_name', models.CharField(max_length=150)),
                ('casual_sick_quota', models.IntegerField(default=12)),
                ('casual_sick_used', models.IntegerField(default=0)),
                ('optional_holiday_quota', models.IntegerField(default=5)),
                ('optional_holiday_used', models.IntegerField(default=0)),
                ('mandatory_holiday_count', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAuditLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(max_length=150)),
                ('admin_name', models.CharField(max_length=150)),
                ('leave_type', models.CharField(max_length=50)),
                ('old_balance', models.IntegerField(default=0)),
                ('new_balance', models.IntegerField(default=0)),
                ('adjustment', models.IntegerField(default=0)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_audit_logs', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enrollment_date', models.CharField(default=django.utils.timezone.now, max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.batch')),
            ],
        ),
    ]
