# Generated by Django 5.2.13 on 2026-09-10 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendancegroupconfig_course_trainerleavebalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('type', models.CharField(default='mandatory', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
