# Generated by Django 5.2.13 on 2026-09-12 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('owner', models.CharField(blank=True, max_length=150, null=True)),
                ('creation', models.CharField(blank=True, max_length=50, null=True)),
                ('invite_link', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
