# Generated by Django 5.2.13 on 2026-09-22 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_whatsappgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('user_role', models.CharField(default='trainer', max_length=50)),
                ('subject', models.CharField(default='Doubt / Support Request', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('unread_admin_count', models.IntegerField(default=0)),
                ('unread_user_count', models.IntegerField(default=0)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_role', models.CharField(default='trainer', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_data', models.TextField(blank=True, null=True)),
                ('attachment_size', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.supportthread')),
            ],
        ),
    ]
