# Generated by Django 5.2.13 on 2026-09-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_supportthread_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportthread',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_threads', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='thread_type',
            field=models.CharField(choices=[('admin_support', 'Admin Support'), ('direct_message', 'Direct Message'), ('faculty_lounge', 'Faculty Lounge')], default='admin_support', max_length=30),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='unread_recipient_count',
            field=models.IntegerField(default=0),
        ),
    ]
