# Generated by Django 5.2.13 on 2026-09-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supportthread_recipient_supportthread_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='demo_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='demo_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='enquiry_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='student_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='student_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('training', 'Training'), ('demo', 'Demo'), ('other', 'Other')], default='training', max_length=20),
        ),
    ]
